"""
config/stocks.py
The ONLY file to edit when adding or removing stocks.
Symbol must be the Yahoo Finance ticker (.NS suffix for NSE stocks).
"""
INDIAN_STOCKS = {
    "M&M":                {"symbol": "M&M.NS",          "sector": "Automobile"},
    "Hero Motocorp":      {"symbol": "HEROMOTOCO.NS",    "sector": "Automobile"},
    "KPIT Technology":    {"symbol": "KPITTECH.NS",      "sector": "IT"},
    "LTM":                {"symbol": "LTIM.NS",          "sector": "IT"},
    "Mphasis":            {"symbol": "MPHASIS.NS",       "sector": "IT"},
    "Maruti":             {"symbol": "MARUTI.NS",        "sector": "Automobile"},
    "DLF":                {"symbol": "DLF.NS",           "sector": "Realty"},
    "Dixon":              {"symbol": "DIXON.NS",         "sector": "Electronics"},
    "SHRIRAM Finance":    {"symbol": "SHRIRAMFIN.NS",    "sector": "Finance"},
    "Indigo":             {"symbol": "INDIGO.NS",        "sector": "Aviation"},
    "Eicher Motors":      {"symbol": "EICHERMOT.NS",     "sector": "Automobile"},
    "Bajaj Auto":         {"symbol": "BAJAJ-AUTO.NS",    "sector": "Automobile"},
    "VEDL":               {"symbol": "VEDL.NS",          "sector": "Metals"},
    "HAL":                {"symbol": "HAL.NS",           "sector": "Defence"},
    "JSW Steel":          {"symbol": "JSWSTEEL.NS",      "sector": "Metals"},
    "LT":                 {"symbol": "LT.NS",            "sector": "Infrastructure"},
    "SBIN":               {"symbol": "SBIN.NS",          "sector": "Banking"},
    "Persistent Systems": {"symbol": "PERSISTENT.NS",    "sector": "IT"},
    "Tata Steel":         {"symbol": "TATASTEEL.NS",     "sector": "Metals"},
    "BHEL":               {"symbol": "BHEL.NS",          "sector": "Capital Goods"},
    "ABB":                {"symbol": "ABB.NS",           "sector": "Capital Goods"},
    "Siemens":            {"symbol": "SIEMENS.NS",       "sector": "Capital Goods"},
    "NTPC":               {"symbol": "NTPC.NS",          "sector": "Power"},
    "National Aluminium": {"symbol": "NATIONALUM.NS",    "sector": "Metals"},
    "Kaynes":             {"symbol": "KAYNES.NS",        "sector": "Electronics"},
    "MCX":                {"symbol": "MCX.NS",           "sector": "Finance"},
    "BSE":                {"symbol": "BSE.NS",           "sector": "Finance"},
    "Trent":              {"symbol": "TRENT.NS",         "sector": "Retail"},
    "Asian Paints":       {"symbol": "ASIANPAINT.NS",    "sector": "Consumer"},
    "OFSS":               {"symbol": "OFSS.NS",          "sector": "IT"},
    "Hindalco":           {"symbol": "HINDALCO.NS",      "sector": "Metals"},
    "Cummins India":      {"symbol": "CUMMINSIND.NS",    "sector": "Capital Goods"},
    "TCS":                {"symbol": "TCS.NS",           "sector": "IT"},
    "Infosys":            {"symbol": "INFY.NS",          "sector": "IT"},
    "Tata Elxsi":         {"symbol": "TATAELXSI.NS",     "sector": "IT"},
    "Bajaj Finance":      {"symbol": "BAJFINANCE.NS",    "sector": "Finance"},
    "Polycab":            {"symbol": "POLYCAB.NS",       "sector": "Electronics"},
    "ICICI Bank":         {"symbol": "ICICIBANK.NS",     "sector": "Banking"},
    "Lupin":              {"symbol": "LUPIN.NS",         "sector": "Pharma"},
    "Laurus Labs":        {"symbol": "LAURUSLABS.NS",    "sector": "Pharma"},
    "NIFTY 50":           {"symbol": "^NSEI",            "sector": "Index"},
}
